import { CvData, IdCardProject, PdfDocument, PortfolioData, SocialLinkSetting, SponsorAd, CustomTemplate, NotificationItem } from '../types';

export const ADMIN_EMAIL = 'arielmethran@gmail.com';
export const ADMIN_PHONE = '0795211686';
export const ADMIN_PASS = 'ariel4ever';
export const ADMIN_INSTAGRAM = '3under57';

export const INITIAL_SOCIAL_LINKS: SocialLinkSetting[] = [
  {
    id: 'soc-1',
    platform: 'instagram',
    handle: '@3under57',
    url: 'https://instagram.com/3under57',
    active: true,
    followersCount: '52.4K',
  },
  {
    id: 'soc-2',
    platform: 'whatsapp',
    handle: '+250 795 211 686',
    url: 'https://wa.me/250795211686',
    active: true,
  },
  {
    id: 'soc-3',
    platform: 'twitter',
    handle: '@SmartTemplatesHQ',
    url: 'https://twitter.com/3under57',
    active: true,
    followersCount: '18.2K',
  },
  {
    id: 'soc-4',
    platform: 'youtube',
    handle: 'Smart Templates Rwanda',
    url: 'https://youtube.com/@smarttemplates',
    active: true,
  },
];

export const INITIAL_ADS: SponsorAd[] = [
  {
    id: 'ad-1',
    sponsorName: 'Kigali Digital Tech Solutions',
    title: 'Supercharge Your Online Business in Rwanda & Beyond',
    description: 'Get 40% discount on Web Development, Cloud hosting, and branding services with code SMART2026.',
    bannerImageUrl: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&q=80',
    targetUrl: 'https://instagram.com/3under57',
    placement: 'login_form',
    active: true,
    momoPayerPhone: '0795211686',
    momoReference: 'MOMO-KDTS-8849',
    momoStatus: 'paid',
    amountRwF: 150000,
    startDate: '2026-08-01',
    endDate: '2026-09-30',
    clicks: 428,
  },
  {
    id: 'ad-2',
    sponsorName: 'Rwanda Creative Media Hub',
    title: 'Hire Certified Designers & Photographers in Kigali',
    description: 'Looking for top-tier visual branding? Connect with verified creators across East Africa.',
    bannerImageUrl: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&q=80',
    targetUrl: 'https://instagram.com/3under57',
    placement: 'one_click',
    active: false,
    momoPayerPhone: '0795211686',
    momoReference: 'MOMO-RCM-9932',
    momoStatus: 'paid',
    amountRwF: 200000,
    startDate: '2026-08-10',
    endDate: '2026-10-10',
    clicks: 812,
  },
];

export const SAMPLE_PDF_DOC: PdfDocument = {
  id: 'doc-default',
  title: 'Global Tech Partnership & Service Agreement',
  category: 'business',
  author: 'Ariel Methran',
  date: '2026-08-19',
  themeColor: '#8b5cf6',
  updatedAt: new Date().toISOString(),
  blocks: [
    {
      id: 'blk-1',
      type: 'heading',
      content: 'SMART TEMPLATES INNOVATION PROPOSAL',
      fontSize: 26,
      textColor: '#9333ea',
      align: 'center',
      bold: true,
    },
    {
      id: 'blk-2',
      type: 'callout',
      content: 'EXECUTIVE SUMMARY: This document outlines the strategic partnership between Smart Templates and leading organizations for AI-assisted digital publishing, automated CV generation, and verified ID issuance.',
      bgColor: 'rgba(147, 51, 234, 0.15)',
      textColor: '#e9d5ff',
      align: 'left',
    },
    {
      id: 'blk-3',
      type: 'heading',
      content: '1. Objective & Scope of Services',
      fontSize: 20,
      textColor: '#38bdf8',
      align: 'left',
      bold: true,
    },
    {
      id: 'blk-4',
      type: 'paragraph',
      content: 'Smart Templates provides state-of-the-art document creation suites allowing students, freelance professionals, educational institutions, and corporate enterprises to draft polished PDF contracts, professional resumes, interactive portfolios, and staff identification badges seamlessly with both AI-powered and manual precision.',
      align: 'justify',
    },
    {
      id: 'blk-5',
      type: 'bullet-list',
      content: 'Instant AI Document Proofreading & Grammar Rectification\nAutomated Mobile Money (MTN & Airtel Rwanda) Sponsorship Ingress\nBatch Identification Card Card-Press with Barcode Synchronization\nDirect Instagram Bio Synchronizer and Subdomain Routing',
      align: 'left',
    },
    {
      id: 'blk-6',
      type: 'signature',
      content: 'Authorized Signatory:\nAriel Methran, Chief Executive Officer\nSmart Templates Ltd, Kigali - Rwanda',
      align: 'right',
      italic: true,
      textColor: '#a855f7',
    },
  ],
};

export const SAMPLE_CV_DATA: CvData = {
  id: 'cv-default',
  fullName: 'Ariel Methran',
  jobTitle: 'Lead Software Architect & Creative Technologist',
  email: 'arielmethran@gmail.com',
  phone: '+250 795 211 686',
  address: 'Kigali City, Rwanda',
  website: 'https://ariel.smarttemplate.com',
  linkedin: 'linkedin.com/in/arielmethran',
  github: 'github.com/arielmethran',
  photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&q=80',
  summary: 'Innovative and results-driven Software Engineer & Systems Architect with 6+ years of expertise in crafting responsive cloud platforms, AI-assisted workflows, cross-platform applications, and high-conversion UX designs. Passionate about empowering individuals and businesses through intuitive digital templates.',
  experiences: [
    {
      id: 'exp-1',
      company: 'Smart Templates Global',
      position: 'Founder & Principal Tech Lead',
      location: 'Kigali, Rwanda',
      startDate: '2023-01',
      endDate: 'Present',
      current: true,
      description: 'Architected scalable document processing engines supporting real-time AI proofreading, batch ID card generation, and automated social profile sync.',
    },
    {
      id: 'exp-2',
      company: 'Apex Digital Innovation Labs',
      position: 'Senior Full Stack Developer',
      location: 'Kigali / Remote',
      startDate: '2021-03',
      endDate: '2022-12',
      current: false,
      description: 'Engineered high-performance React and Node microservices serving 100k+ active monthly users across East Africa.',
    },
  ],
  education: [
    {
      id: 'edu-1',
      institution: 'University of Rwanda / African Leadership University',
      degree: 'Bachelor of Science',
      fieldOfStudy: 'Computer Science & Software Systems',
      startDate: '2017',
      endDate: '2021',
      grade: 'First Class Honors',
    },
  ],
  skills: [
    'React & TypeScript',
    'Node.js & Express',
    'AI Prompt Engineering',
    'PDF & Canvas Rendering',
    'Tailwind CSS & Motion',
    'Mobile Money API Integration',
    'UI/UX Prototyping',
    'PostgreSQL & Cloud Databases',
  ],
  projects: [
    {
      id: 'proj-1',
      name: 'Smart Templates Cloud Studio',
      description: 'Complete multi-tool suite for PDF docs, resumes, ID badges, and portfolio generation with direct Instagram bio linking.',
      tools: 'React 19, Gemini AI, Tailwind, jsPDF',
    },
    {
      id: 'proj-2',
      name: 'MoMo Direct Rwanda Gateway',
      description: 'Automated manual USSD MoMo payment verification dashboard for local SME sponsors.',
      tools: 'Node.js, Express, WebSockets',
    },
  ],
  languages: ['English (Fluent)', 'Kinyarwanda (Native)', 'French (Professional)'],
  certifications: [
    'Google Cloud Certified Professional Cloud Architect',
    'Meta Certified Front-End Developer',
  ],
  templateId: 'modern-vibrant',
  primaryColor: '#8b5cf6',
  accentColor: '#ec4899',
  updatedAt: new Date().toISOString(),
};

export const SAMPLE_PORTFOLIO: PortfolioData = {
  id: 'port-default',
  username: 'ariel',
  fullName: 'Ariel Methran',
  nickname: 'Ari / CodeMaster',
  title: 'Digital Creator, Designer & Developer',
  bio: 'Building colorful, powerful tools that turn creative ideas into reality. Lover of modern aesthetics, African tech innovation, vibrant graphics, and smooth user experiences.',
  address: 'KG 14 Ave, Kigali, Rwanda',
  email: 'arielmethran@gmail.com',
  phone: '0795211686',
  photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
  instagramHandle: '3under57',
  preferences: {
    favoriteFood: 'Brochettes with Plantains & Fresh Avocado',
    favoriteSong: 'Jerusalema & Rwandan Afrobeat Hits',
    favoriteArtist: 'Meddy, The Weeknd & Stromae',
    favoriteMovie: 'Interstellar & The Social Network',
    hobbies: 'Coding creative apps, graphic design, football, photography',
    quote: 'Design is not just what it looks like and feels like. Design is how it works.',
  },
  skills: [
    'Web Architecture',
    'Creative Direction',
    'AI Tools Specialist',
    'Mobile Money Integration',
    'Document Automation',
    'Visual Branding',
  ],
  galleryImages: [
    {
      id: 'img-1',
      url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80',
      title: 'Neon Aurora 3D Concept',
      category: 'Design',
    },
    {
      id: 'img-2',
      url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80',
      title: 'Cyberpunk Workspace',
      category: 'Tech',
    },
    {
      id: 'img-3',
      url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80',
      title: 'Code Matrix Architecture',
      category: 'Software',
    },
    {
      id: 'img-4',
      url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&q=80',
      title: 'Vibrant Lightwaves',
      category: 'Art',
    },
  ],
  socialLinks: [
    {
      platform: 'instagram',
      url: 'https://instagram.com/3under57',
      handle: '3under57',
    },
    {
      platform: 'whatsapp',
      url: 'https://wa.me/250795211686',
      handle: '+250 795 211 686',
    },
    {
      platform: 'github',
      url: 'https://github.com/arielmethran',
      handle: 'arielmethran',
    },
  ],
  theme: 'vibrant-aurora',
  customSubdomain: 'ariel.smarttemplate.com',
  instagramSynced: true,
  updatedAt: new Date().toISOString(),
};

export const SAMPLE_ID_PROJECT: IdCardProject = {
  id: 'id-proj-default',
  mode: 'company',
  organizationName: 'KIGALI TECH INSTITUTE & INNOVATION HUB',
  organizationLogoUrl: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=300&q=80',
  templateStyle: 'modern-vertical',
  primaryColor: '#7c3aed',
  secondaryColor: '#06b6d4',
  activeCardIndex: 0,
  updatedAt: new Date().toISOString(),
  cards: [
    {
      id: 'c-1',
      fullName: 'Ariel Methran',
      idNumber: 'KTI-2026-0042',
      cardType: 'staff',
      roleOrClass: 'Head of Software Development',
      departmentOrSchool: 'Faculty of Computing & Informatics',
      validUntil: '31 DEC 2028',
      issueDate: '01 JAN 2026',
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&q=80',
      bloodGroup: 'O+',
      emergencyPhone: '+250 795 211 686',
      barcode: '98432094821',
    },
    {
      id: 'c-2',
      fullName: 'Clarisse Umutoni',
      idNumber: 'KTI-2026-0189',
      cardType: 'student',
      roleOrClass: 'Year 3 - Data Science',
      departmentOrSchool: 'Department of AI & Data Engineering',
      validUntil: '31 DEC 2027',
      issueDate: '01 JAN 2026',
      photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&q=80',
      bloodGroup: 'A+',
      emergencyPhone: '+250 788 123 456',
      barcode: '98432094822',
    },
    {
      id: 'c-3',
      fullName: 'David Mugisha',
      idNumber: 'KTI-2026-0210',
      cardType: 'student',
      roleOrClass: 'Year 2 - Cyber Security',
      departmentOrSchool: 'Network Security Lab',
      validUntil: '31 DEC 2027',
      issueDate: '01 JAN 2026',
      photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&q=80',
      bloodGroup: 'B+',
      emergencyPhone: '+250 783 999 888',
      barcode: '98432094823',
    },
  ],
};

export const DEFAULT_TEMPLATES_LIST: CustomTemplate[] = [
  {
    id: 'tmpl-cv-1',
    category: 'cv',
    title: 'Vibrant Neon Executive CV',
    description: 'High-impact colorful modern layout with skill badges, gradient highlights, and clean typography.',
    previewImageUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&q=80',
    isAiGenerated: false,
    data: {
      templateId: 'modern-vibrant',
      primaryColor: '#8b5cf6',
      accentColor: '#ec4899',
    },
    createdAt: '2026-08-01',
  },
  {
    id: 'tmpl-cv-2',
    category: 'cv',
    title: 'Emerald Clean Tech Resume',
    description: 'Crisp green & slate accents designed for developers, data engineers, and IT leaders.',
    previewImageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80',
    isAiGenerated: false,
    data: {
      templateId: 'creative-glow',
      primaryColor: '#10b981',
      accentColor: '#06b6d4',
    },
    createdAt: '2026-08-05',
  },
  {
    id: 'tmpl-pdf-1',
    category: 'pdf',
    title: 'Formal Business Partnership Agreement',
    description: 'Complete legal contract layout with executive header, clauses, bulleted terms, and signature block.',
    previewImageUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600&q=80',
    isAiGenerated: false,
    data: {},
    createdAt: '2026-08-08',
  },
  {
    id: 'tmpl-id-1',
    category: 'idcard',
    title: 'Modern Holographic Student ID',
    description: 'Vertical layout with prominent badge, QR code, blood group, barcode, and anti-counterfeit neon stripes.',
    previewImageUrl: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&q=80',
    isAiGenerated: false,
    data: {
      templateStyle: 'modern-vertical',
      primaryColor: '#7c3aed',
      secondaryColor: '#06b6d4',
    },
    createdAt: '2026-08-10',
  },
  {
    id: 'tmpl-id-2',
    category: 'idcard',
    title: 'Corporate Staff Access Badge',
    description: 'Horizontal corporate card layout with department, security clearance level, and emergency contact.',
    previewImageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&q=80',
    isAiGenerated: false,
    data: {
      templateStyle: 'corporate-horizontal',
      primaryColor: '#0284c7',
      secondaryColor: '#f59e0b',
    },
    createdAt: '2026-08-12',
  },
  {
    id: 'tmpl-port-1',
    category: 'portfolio',
    title: 'Aurora Creator Portfolio with Instagram Bio Link',
    description: 'Dynamic personal portfolio highlighting your favorites, bio, gallery, and seamless Instagram sync.',
    previewImageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&q=80',
    isAiGenerated: false,
    data: {},
    createdAt: '2026-08-14',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Welcome to Smart Templates 2026',
    message: 'Explore our 5 studios: PDF, CV, Portfolio, ID Cards, and Picture Studio with AI tools!',
    date: 'Today',
    read: false,
    type: 'info',
    linkTab: 'home',
  },
  {
    id: 'notif-2',
    title: 'MoMo Sponsorship Support',
    message: 'Promote your brand in Rwanda via MTN or Airtel MoMo to 0795211686.',
    date: 'Today',
    read: false,
    type: 'sponsor',
    linkTab: 'sponsorship',
  },
  {
    id: 'notif-3',
    title: 'New AI Quality Engine',
    message: 'AI now checks missing contact information, punctuation gaps, and spelling typos across your CV and documents.',
    date: 'Today',
    read: false,
    type: 'info',
    linkTab: 'cv',
  },
];

export const initialNotifications = INITIAL_NOTIFICATIONS;
export const initialTemplates = DEFAULT_TEMPLATES_LIST;
export const initialAds = INITIAL_ADS;
export const initialPdfDoc = SAMPLE_PDF_DOC;
export const initialCvData = SAMPLE_CV_DATA;
export const initialPortfolioData = SAMPLE_PORTFOLIO;
export const initialIdCardData = SAMPLE_ID_PROJECT;
export const initialPictureProject = {
  id: 'pic-1',
  title: 'Creative Portrait',
  currentImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80',
  originalImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80',
  filters: {
    name: 'vibrant-glow',
    brightness: 105,
    contrast: 110,
    saturation: 125,
    smoothLevel: 30,
    warmth: 10,
  },
  updatedAt: new Date().toISOString(),
};
